let
    Source = GoldLayerTable,
    AddedKey = Table.AddColumn(
        Source,
        "SurrogateKey",
        each fnMD5Hash([Plant Cd] & [Production Area Cd]),
        type text
    )
in
    AddedKey
